/* This file was generated by syncqt with the info from sync.profile. */
#ifndef QT_QTLOCATION_VERSION_H
#define QT_QTLOCATION_VERSION_H

#define QTLOCATION_VERSION_STR "5.0.0"

#define QTLOCATION_VERSION 0x050000

#endif // QT_QTLOCATION_VERSION_H
